# == Define: t
#
# This is a wrapper around the built-in puppet type 'file'.
# It creates a root:root:0644 file from an ERB template with the same name (the target directory must exist).
#
# === Parameters
#
# [*title*]
#   Contains the directory to create.
#
# [*source*]
#   This parameter is autogenerated from caller_module_name/title.erb.
#   If you overwrite this parameter this means that you want to determine the source file yourself.
#
# [*owner*]
#   File owner
#
# [*group*]
#   File group
#
# === Examples
#
#   This will fetch the file from puppet/modules/<modulename>/templates/etc/motd.erb:
#
#   t { "/etc/motd": }
#
# === Authors
#
# Alexander.Gabert <alexander@midokura.com>
#
define t (
  $c = "${caller_module_name}"
  $source = "${c}/${title}.erb",
  $mode = '0644',
  $owner = 'root',
  $group = 'root',
  ) {
  file {"t_TEMPLATE_${source}_TO_${title}":
    ensure => "file",
    path => "${title}",
    content => template("${source}"),
    mode => "${mode}",
    owner => "${owner}",
    group => "${group}",
  }
}

