---
driver:
  name: docker
  use_sudo: false

provisioner:
  name: puppet_apply
  manifests_path: test
  modules_path: modules
  hiera_data_path: data
  hiera_config_path: data/hiera.yaml
  manifest: init.pp

platforms:
  - name: ubuntu-12.04
    driver_config:
        image: midonet/ubuntu:12.04
  - name: ubuntu-14.04
    driver_config:
        image: midonet/ubuntu:14.04
  - name: centos-6.6
    driver_config:
        image: midonet/centos:centos6
        privileged: true
  - name: centos-7
    driver_config:
        image: midonet/centos:centos7
        privileged: true

suites:
  - name: default
